#key : value
sehirler = {
    1 : "Adana",
    2 : "Adıyaman",
    3 : "Afyonkarahisar",
    4 : "Ağrı",
    5 : "Amasya",
    6 : "Ankara",
    7 : "Antalya",
    8 : "Artvin",
    9 : "Aydın",
    10: "Balıkesir",
    11: "Bilecik",
    12: "Bingöl",
    13: "Bitlis",
    14: "Bolu",
    15: "Burdur",
    16: "Bursa",
    17: "Çanakkale",
    18: "Çankırı",
    19: "Çorum",
    20: "Denizli",
    21: "Diyarbakır",
    22: "Edirne",
    23: "Elazığ",
    24: "Erzincan",
    25: "Erzurum",
    26: "Eskişehir",
    27: "Gaziantep",
    28: "Giresun",
    29: "Gümüşhane",
    30: "Hakkari",
    31: "Hatay",
    32: "Isparta",
    33: "Mersin",
    34: "İstanbul",
    35: "İzmir",
    36: "Kars",
    37: "Kastamonu",
    38: "Kayseri",
    39: "Kırklareli",
    40: "Kırşehir",
    41: "Kocaeli",
    42: "Konya",
    43: "Kütahya",
    44: "Malatya",
    45: "Manisa",
    46: "Kahramanmaraş",
    47: "Mardin",
    48: "Muğla",
    49: "Muş",
    50: "Nevşehir",
    51: "Niğde",
    52: "Ordu",
    53: "Rize",
    54: "Sakarya",
    55: "Samsun",
    56: "Siirt",
    57: "Sinop",
    58: "Sivas",
    59: "Tekirdağ",
    60: "Tokat",
    61: "Trabzon",
    62: "Tunceli",
    63: "Şanlıurfa",
    64: "Uşak",
    65: "Van",
    66: "Yozgat",
    67: "Zonguldak",
    68: "Aksaray",
    69: "Bayburt",
    70: "Karaman",
    71: "Kırıkkale",
    72: "Batman",
    73: "Şırnak",
    74: "Bartın",
    75: "Ardahan",
    76: "Iğdır",
    77: "Yalova",
    78: "Karabük",
    79: "Kilis",
    80: "Osmaniye",
    81: "Düzce"
}
sehirler2 = {
    "adana": "01",
    "adiyaman": "02",
    "afyonkarahisar": "03",
    "agri": "04",
    "amasya": "05",
    "ankara": "06",
    "antalya": "07",
    "artvin": "08",
    "aydin": "09",
    "balikesir": "10",
    "bilecik": "11",
    "bingol": "12",
    "bitlis": "13",
    "bolu": "14",
    "burdur": "15",
    "bursa": "16",
    "canakkale": "17",
    "cankiri": "18",
    "corum": "19",
    "denizli": "20",
    "diyarbakir": "21",
    "edirne": "22",
    "elazig": "23",
    "erzincan": "24",
    "erzurum": "25",
    "eskisehir": "26",
    "gaziantep": "27",
    "giresun": "28",
    "gumushane": "29",
    "hakkari": "30",
    "hatay": "31",
    "isparta": "32",
    "mersin": "33",
    "istanbul": "34",
    "izmir": "35",
    "kars": "36",
    "kastamonu": "37",
    "kayseri": "38",
    "kirklareli": "39",
    "kirsehir": "40",
    "kocaeli": "41",
    "konya": "42",
    "kutahya": "43",
    "malatya": "44",
    "manisa": "45",
    "kahramanmaras": "46",
    "mardin": "47",
    "mugla": "48",
    "mus": "49",
    "nevsehir": "50",
    "nigde": "51",
    "ordu": "52",
    "rize": "53",
    "sakarya": "54",
    "samsun": "55",
    "siirt": "56",
    "sinop": "57",
    "sivas": "58",
    "tekirdag": "59",
    "tokat": "60",
    "trabzon": "61",
    "tunceli": "62",
    "sanliurfa": "63",
    "usak": "64",
    "van": "65",
    "yozgat": "66",
    "zonguldak": "67",
    "aksaray": "68",
    "bayburt": "69",
    "karaman": "70",
    "kirikkale": "71",
    "batman": "72",
    "sirnak": "73",
    "bartin": "74",
    "ardahan": "75",
    "igdir": "76",
    "yalova": "77",
    "karabuk": "78",
    "kilis": "79",
    "osmaniye": "80",
    "duzce": "81"
}
while True:
    veri = input("-->")
    if veri.isdigit():
        print(sehirler.get(int(veri),"böyle bir plaka kodu yok"))
    elif veri.isalpha():
        veri=veri.lower()
        veri=veri.replace("ı","i").replace("ç","c").replace("ö","o").replace("ş","s").replace("ü","u").replace("ğ","g")
        print(sehirler2.get(veri,"böyle bir şehir yok"))
    else:
        print("hatalı giriş yaptınız")